<!-- Conatct Page - Common Page 1 - Most HTML taken from index.php with just removal of carousel and the devices div and addition of the contact form -->
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="img/logo.ico" type="image/png" />
        <title>LifeWin - Habits to Success</title>

        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        <meta property="og:image" content="img/50by50.jpg"/>
		<!-- Change the favicon path in index.php -->
	<link rel="shortcut icon" href="img/favicon.ico"/>
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <![endif]-->
        <script type="text/javascript" src="global.js"></script>
        <script type="text/javascript" src="js/jquery-2.0.3.min.js"></script>
        <meta charset="UTF-8">
        <meta name="author" content="Nitish Kumar">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LifeWin - Habits to Success | Homepage</title>
        <link href="css/icomoon.css" rel="stylesheet" type="text/css">
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="css/style.css" rel="stylesheet" type="text/css">
        <script>
         $(document).on('click', '.signin-fb', function() {
                fblogin = 1;
         });
		 
		 $(document).ready(function(){
			$('#cont_form').submit(function(e) {
				$.ajax({
				type: "POST",
				url: "contact-send.php",
				data: $('#cont_form').serialize(),
				dataType: "json",
				success: function(msg){
					 var x = parseInt(msg.status);
						  switch(x){
							case 0 :
								$('.cont_err').html(msg.txt);$('.cont_error').hide().fadeIn(300);break;
						 } 
					}
				});
			e.preventDefault();	
			});
		 });
        </script>
    </head>
    <body>
        <div class="selection-error" style="display: none;"></div>
        <div class="selection-success" style="display: none;"></div>
        <div id="fb-root"></div>
        <div class="modal fade" id="login_signup_box">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-6 loginbox">
                                <h4 class="modal-title">Login to your account</h4>
                                <div class="form-group">
                                    <a href="php/login/fblogin.php" class="signin-fb btn btn-primary btn-fb">Login With Facebook</a>
                                    <a href="php/login/gmaillogin.php" class="btn btn-danger btn-google">Login With Google</a>  
                                </div>

                                <div class="form-group">
                                    <img src="img/sep.png" alt="">
                                </div>
                                <div class="clearfix"></div>
                                <form method="post" name="userlogin" action="userLogin.php">
                                    <div class="form-group">
                                        <input id="email" class="form-control" type="text" name="email" title="Enter Email" placeholder="Email" onchange="jsemail()" pattern="([a-zA-Z0-9._-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z]+)*)" required autofocus>
										<!-- The @ has been added infront of the php echo variable in order to prevent error reports generated by php as for the first time the variables are executed they will be empty-->
                                        <span style="color:#e11" id="err-email"><?php echo @$err['email']; ?></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" name="password" id="password_login" placeholder="Password">
                                    </div>
                                    <div class="form-group text-left">
                                        <button type="submit" name="login" value="userlogin" class="btn btn-primary btnlogin">Login</button>
                                        <button type="submit" name="resetpass" value="resetpass" class="btn btn-danger btnresetpass">Reset Password</button>
                                        <p class="text-left pull-right"><a id="forgetPass" href="#">Forgot Password </a></p>
                                    </div>
                                </form>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-6 signup">
                                <h4 class="modal-title">Sign up</h4>
                                <form method="post" name="signup" action="php/signup.php" onsubmit="return jssignup()">
                                    <div class="form-group">
                                    	<input type="text" class="form-control" id="fname" name="fname" title="Enter your First Name" placeholder="First Name" autofocus onchange="jsname()" style="text-transform:capitalize" pattern="^[A-Za-z][A-Za-z. ]+$" required>
										<!-- The @ has been added infront of the php echo variable in order to prevent error reports generated by php as for the first time the variables are executed they will be empty-->
                                    	<span class="error" id="err-name"><?php echo @$err['fname']; ?></span>
                                    </div>
                                    <div class="form-group">
                                    	<input type="text" class="form-control" id="lname" name="lname" title="Enter your Last Name" placeholder="Last Name" autofocus onchange="jsname()" style="text-transform:capitalize" pattern="^[A-Za-z][A-Za-z. ]+$" required>
										<!-- The @ has been added infront of the php echo variable in order to prevent error reports generated by php as for the first time the variables are executed they will be empty-->
                                    	<span class="error" id="err-name"><?php echo @$err['lname']; ?></span>
                                    </div> 
                                    <div class="form-group">
                                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" onchange="jsemail()" required>
										<!-- The @ has been added infront of the php echo variable in order to prevent error reports generated by php as for the first time the variables are executed they will be empty-->
                                        <span class="error" id="err-email"><?php echo @$err['email']; ?></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="password" name="password" title="Minimum 5 characters long" placeholder="Password" onchange="jspassword()" maxlength="20" pattern="^.{5,20}$" required>
										<!-- The @ has been added infront of the php echo variable in order to prevent error reports generated by php as for the first time the variables are executed they will be empty-->
                                        <span class="error" id="err-password"><?php echo @$err['password']; ?></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" placeholder="Confirm Password" title="Re-enter yout password" onchange="jspassword()" maxlength="20" pattern="^.{5,20}$" required>
										<!-- The @ has been added infront of the php echo variable in order to prevent error reports generated by php as for the first time the variables are executed they will be empty-->
                                        <span class="error" id="err-password"><?php echo @$err['password']; ?></span>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" name="signup" value="signup" class="btn btn-danger">Sign Up</button>
                                    </div>
                                </form>
                            </div>
							
                        </div>

                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <header>
            <div id="headerNav">
                <div class="container">
                    <div class="row">
                        <nav class="navbar navbar-default" role="navigation">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header col-md-3">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-menu">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <h1 id="logo"><a href="http://lifewin.co/index.php"><img src="img/logo.png" height="65" width="135" alt="logo" ></a></h1>
                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-menu">
                                    <ul class="nav navbar-nav">
                                        <li class="active"><a href="index.php">Home</a></li>
                                        <li><a href="benefits.html">Benefits</a></li>
                                        <li><a href="solutions.html">Solutions</a></li>
                                        <li><a href="http://blog.lifewin.co">Blog</a></li>
                                    </ul>

                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a href="#" data-toggle="modal" data-target="#login_signup_box">Signup/Login</a></li>
                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>            
                    </div><!--row-->
                </div><!--container-->
            </div><!--headernav-->
        </header>
        <div style="color:red;"><?php if(isset($_SESSION['error'])) { echo $_SESSION['error']; unset($_SESSION['error']);}?></div>
        <div class="success-msg"><?php if(isset($_SESSION['success'])) { echo $_SESSION['success']; unset($_SESSION['success']);}?></div>
        <div class="clearfix"></div>

        <div class="clearfix"></div>

        <section id="home_devices">
            <div class="container">
                <div class="row">
                    <div class = "contact-form-div col-md-6 col-sm-12">
						<h1 class = "title-head">Contact Us</h1>
						<form method = "POST" id = "cont_form">
							<input type = "text" class = "form-control custom-control" name = "name" placeholder = "Your Name" title = "Your Name">
							<input type = "text" class = "form-control custom-control" name = "email" placeholder = "Your Email" title = "Your Email">
							<textarea class = "form-control custom-control txt_cust" placeholder = "Your Message" rows = "6" title = "Your Message"name = "query" ></textarea>
							<input type = "submit" class = "btn1" value = "Send Query">
							<span class="alert alert-danger cont_error hides">
								<strong><span class = "cont_err"></span></strong>
							</span>
						</form>
					</div>
					<!-- Contact Information -->
				<div class="col-sm-12 col-md-6 pull-left text-center addr-text">
					<address>
						<strong>12.	LifeWin Solutions </strong>
						<br>1 Dreams Lane
						<br>Over Sky, IND 1111
						<br>
					</address>
					<address>
						<abbr title="Phone">Phone:</abbr>(123) 456-7890
						<br>
						<abbr title="Email">Email:</abbr> <a href="mailto:contact@lifewin.co">contact@lifewin.co</a>
					</address>
				</div>
				</div>
				</div>
			</div>	
            <div class="signup_section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>What will you do to win?</h2>
                            <button class="btn1">Get Started!</button>

                        </div>
                    </div>
                </div>
            </div><!--signup section-->    

            <div class="clearfix"></div>
            <!--Testimonials, to be included, when the we have some {adding hide class will not show testimonial } -->
            <div class="container hide">
                <div class="row">
                    <div class="col-md-12">

                        <div class="home_testimonial">
                            <h2>What the users say</h2>
                            <div id="carousel-testimonial" class="carousel slide" data-ride="carousel">
                                <!-- Wrapper for slides -->

                                <div class="carousel-inner">
                                    <div class="item active">
                                        <img src="img/user1.png" alt="slide1" class="img-responsive" />
                                        <div class="carousel-caption_user">
                                            <h5>Jenna Sue</h5>
                                            <p>"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. "</p>
                                        </div>
                                    </div>

                                    <div class="item">
                                        <img src="img/user1.png" alt="slide1" class="img-responsive" />
                                        <div class="carousel-caption_user">
                                            <h5>Jenna Sue</h5>
                                            <p>"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. "</p>
                                        </div>
                                    </div>        

                                    <div class="item">
                                        <img src="img/user1.png" alt="slide1" class="img-responsive" />
                                        <div class="carousel-caption_user">
                                            <h5>Jenna Sue</h5>
                                            <p>"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. "</p>
                                        </div>
                                    </div>    
                                </div><!--carousel-inner-->
                                <!-- Controls -->
                                <a class="left carousel-control" href="#carousel-testimonial" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#carousel-testimonial" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>    
        </section>

        <div class="clearfix"></div>

        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <h3><a href="http://lifewin.co/">LifeWin</a></h3>
                        <p>A New Generation Personal Productivity App</p>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <h3>Company</h3>
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><a href="benefits.html">Benefits</a></li>
                            <li><a href="solutions.html">Solutions</a></li>
                            <li><a href="http://blog.lifewin.co">Blog</a></li>
                        </ul>
                    </div> 
                    <div class="col-sm-6 col-md-3">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Terms & Condition</a></li>
                            <li><a href="#">Features</a></li>
                            <li><a href="#">FAQ's</a></li>
                        </ul>
                    </div> 
                    <div class="col-sm-6 col-md-3">
                        <h3> Social </h3>
                        <ul>
                            <li><a target="_blank" href="https://www.facebook.com/lifewinapp">
                                    <img src="img/fb.png" alt="LifeWin Facebook Page" class="img-responsive" />
                                    facebook.com/LifeWinApp
                                </a></li>
                            <li><a target="_blank" href="https://twitter.com/lifewinapp">
                                    <img src="img/twitter.png" alt="LifeWin Twitter Page" class="img-responsive" />
                                    twitter.com/LifeWinApp
                                </a></li>
                            <li><a target="_blank" href="http://www.reddit.com/r/lifewin/">
                                    <img src="img/reddit.png" alt="LifeWin sub-reddit" class="imag-responsive" height="32" width="32"/>
                                    reddit.com/r/LifeWin
                                </a></li>
                            <!--Link to Google Profile hidden, as we have none
        <li><a target="_blank" href="#"><img src="img/google.png" alt="" class="img-responsive" /></a></li>-->
                        </ul>
                    </div>                        
                </div>
            </div>
        </footer>


        <script type="text/javascript" charset="utf-8" src="js/jquery-2.0.3.min.js"></script> 
        <script type="text/javascript" charset="utf-8" src="js/bootstrap.min.js"></script> 
        <script type="text/javascript" charset="utf-8" src="js/custom.js"></script>
        <script type="text/javascript" charset="utf-8" src="js/jquery.flexisel.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $(document).on('click', '#forgetPass', function(event) {
                    event.preventDefault();
                    $('.btnlogin,#password_login').hide();
                    $('.btnresetpass').show();
                    $('#forgetPass').text('Sign In');
                    $('#forgetPass').addClass('signin');
                });
                $(document).on('click', '#forgetPass.signin', function(event) {
                    event.preventDefault();
                    $('.btnlogin,#password_login').show();
                    $('.btnresetpass').hide();
                    $('#forgetPass').text('Forgot Password');
                    $('#forgetPass').removeClass('signin');
                });
            });
            
            function alert_sucess(msg){
                $('.selection-success').html('<div class="alert alert-success">'+ msg +'</div>');
                $('.selection-success').fadeIn('slow');
                $('.selection-success').addClass('open');
                setTimeout(function(){
                    $('.selection-success').removeClass('open');
                    $('.selection-success').fadeOut('slow');
                    
                },2000);
            }
            function alert_error(msg){
                $('.selection-error').html('<div class="alert alert-danger">'+ msg +'</div>');
                $('.selection-error').fadeIn('slow');
                $('.selection-error').addClass('open');
                setTimeout(function(){
                    $('.selection-error').removeClass('open');
                    $('.selection-error').fadeOut('slow');
                     
                },2000);
            } 
        </script>
    </body>
</html>
